test zap gittoken

diff --git a/.github/workflows/devdelpoy.yaml b/.github/workflows/devdelpoy.yaml
--- a/.github/workflows/devdelpoy.yaml
+++ b/.github/workflows/devdelpoy.yaml
@@ -75,71 +75,71 @@ jobs:
           name: error-files
           path: build_errors.log
 
-  run-web-and-test:
-    name: Run Web and Playwright Tests
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout Web repository
-        uses: actions/checkout@v3
-        with:
-          repository: Theerapat-dev/PresidentDemo-Web
-          token: ${{ secrets.GH_PAT }}
-          ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
+  # run-web-and-test:
+  #   name: Run Web and Playwright Tests
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - name: Checkout Web repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: Theerapat-dev/PresidentDemo-Web
+  #         token: ${{ secrets.GH_PAT }}
+  #         ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '16'
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '16'
 
-      - name: Set npm registry
-        run: npm config set registry https://registry.npmjs.org/
+  #     - name: Set npm registry
+  #       run: npm config set registry https://registry.npmjs.org/
 
-      - name: Install dependencies
-        run: npm install --force
+  #     - name: Install dependencies
+  #       run: npm install --force
 
-      - name: Start the app
-        run: |
-          npm start &
-          npx wait-on http://localhost:4200
-        env:
-          PORT: 4200
+  #     - name: Start the app
+  #       run: |
+  #         npm start &
+  #         npx wait-on http://localhost:4200
+  #       env:
+  #         PORT: 4200
 
-      - name: Install Playwright
-        run: npx playwright install
+  #     - name: Install Playwright
+  #       run: npx playwright install
 
-      - name: Run Playwright tests
-        id: run-tests
-        run: |
-          npx playwright test --output=results.json || exit 1
-          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
-            echo "Tests failed."
-            exit 1
-          else
-            echo "Tests passed."
-          fi
+  #     - name: Run Playwright tests
+  #       id: run-tests
+  #       run: |
+  #         npx playwright test --output=results.json || exit 1
+  #         if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+  #           echo "Tests failed."
+  #           exit 1
+  #         else
+  #           echo "Tests passed."
+  #         fi
 
-      - name: Upload test results
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: playwright-results
-          path: results.json
+  #     - name: Upload test results
+  #       if: always()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: playwright-results
+  #         path: results.json
 
-      - name: Create screenshots directory
-        if: always()
-        run: mkdir -p screenshots
+  #     - name: Create screenshots directory
+  #       if: always()
+  #       run: mkdir -p screenshots
 
-      - name: Upload Screenshots
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: playwright-screenshots
-          path: screenshots/failure.png
+  #     - name: Upload Screenshots
+  #       if: always()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: playwright-screenshots
+  #         path: screenshots/failure.png
 
   ZAP_Full_Scan_Before:
     runs-on: ubuntu-latest
-    needs: run-web-and-test
+    needs: build
     name: ZAP_Full_Scan_Before
     steps:
       - name: Checkout
@@ -166,7 +166,7 @@ jobs:
 
   ZAP_API_Scan_Before:
     runs-on: ubuntu-latest
-    needs: run-web-and-test
+    needs: build
     name: ZAP_API_Scan_Before
     steps:
       - name: Checkout
@@ -200,7 +200,7 @@ jobs:
         dependabot,
         lint,
         build,
-        run-web-and-test,
+        # run-web-and-test,
         ZAP_Full_Scan_Before,
         ZAP_API_Scan_Before,
       ]
@@ -374,7 +374,6 @@ jobs:
             report_md.md
             report_html.html
 
-
   trigger_jenkins:
     name: Trigger Jenkins Job
     runs-on: ubuntu-latest
@@ -450,7 +449,7 @@ jobs:
         dependabot,
         lint,
         build,
-        run-web-and-test,
+        # run-web-and-test,
         ZAP_Full_Scan_Before,
         ZAP_API_Scan_Before,
         push_to_registry,
@@ -526,7 +525,7 @@ jobs:
         dependabot,
         lint,
         build,
-        run-web-and-test,
+        # run-web-and-test,
         ZAP_Full_Scan_Before,
         ZAP_API_Scan_Before,
         push_to_registry,
