หแ

diff --git a/.github/workflows/fateone.yml b/.github/workflows/fateone.yml
--- a/.github/workflows/fateone.yml
+++ b/.github/workflows/fateone.yml
@@ -78,12 +78,12 @@ jobs:
       - name: Build Project
         id: build
         run: |
-          npm run build 2> build_errors.log
+          npm run build 2> build_errors.log || true
           exit_code=$?
-          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_OUTPUT
-
+          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
+          exit $exit_code
       - name: Upload Error Files
-        if: ${{ steps.build.outputs.error_files_present == 'true' || always() }}
+        if: ${{ env.error_files_present == 'true' || always() }}
         uses: actions/upload-artifact@v3
         with:
           name: error-files
@@ -188,109 +188,118 @@ jobs:
             report_html.html
 
   send_failure_notification:
-              name: Send Failure Notification
-              runs-on: ubuntu-lates
-              needs: [build,ZAP_API_Scan_Before ]
-              if: ${{ failure() }}
-              concurrency:
-                group: send-failure-notification-${{ github.ref }}
-                cancel-in-progress: false
-              steps:
-                - name: Checkout Code
-                  uses: actions/checkout@v3
-                  with:
-                    fetch-depth: 0  # Fetch all history
+    name: Send Failure Notification
+    runs-on: ubuntu-latest
+    needs: [
+        dependabot,
+        lint,
+        build,
+        # run-web-and-test,
+        # ZAP_Full_Scan_Before,
+        ZAP_API_Scan_Before,
+      ]
+    if: ${{ failure() }}
+    concurrency:
+      group: send-failure-notification-${{ github.ref }}
+      cancel-in-progress: false
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch all history
 
-                - name: Download Error Files
-                  uses: actions/download-artifact@v3
-                  with:
-                    name: error-files
+      - name: Download Error Files
+        uses: actions/download-artifact@v3
+        with:
+          name: error-files
 
-                - name: Get Error Log and Commit Info
-                  id: error_info
-                  run: |
-                    # Get the author information from the latest commit
-                    COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
+      - name: Get Error Log and Commit Info
+        id: error_info
+        run: |
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
+          if [[ -z "$COMMIT_AUTHOR_EMAIL" ]] || [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
+            if [[ -z "$COMMIT_AUTHOR_EMAIL" ]]; then
+              COMMIT_AUTHOR_EMAIL="default@example.com" # ค่าเริ่มต้นถ้าไม่เจอค่า
+            fi
+          fi
+          changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
+          error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
+          echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
+          non_error_files=""
+          for file in $changed_files; do
+            if ! grep -q "$file" build_errors.log; then
+              non_error_files+="$file "
+            fi
+          done
+          echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
+          echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
 
-                    if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
-                      COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
-                    fi
-
-                    changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-
-                    error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
-                    echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
-
-                    non_error_files=""
-                    for file in $changed_files; do
-                      if ! grep -q "$file" build_errors.log; then
-                        non_error_files+="$file "
-                      fi
-                    done
-
-                    echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
-                    echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
-
-                - name: Send email on failure
-                  uses: dawidd6/action-send-mail@v3
-                  with:
-                    server_address: smtp.gmail.com
-                    server_port: 587
-                    username: ${{ secrets.GMAIL_USERNAME }}
-                    password: ${{ secrets.GMAIL_APP_PASSWORD }}
-                    subject: "Build failure for ${{ github.repository }}"
-                    body: |
-                      Build failed for commit: ${{ github.sha }}
-
-                      Files with errors:
-                      ${{ steps.error_info.outputs.error_paths }}
-
-                      Files changed: ${{ steps.error_info.outputs.non_error_files }}
-
-                    to: ${{ steps.error_info.outputs.commit_author_email }}
-                    from: ${{ secrets.GMAIL_USERNAME }}
-                    attachments: build_errors.log
+      - name: Send email on failure
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.GMAIL_USERNAME }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          subject: "Build failure for ${{ github.repository }}"
+          body: |
+            Build failed for commit: ${{ github.sha }}
+            Files with errors:
+            ${{ steps.error_info.outputs.error_paths }}
+            Files changed: ${{ steps.error_info.outputs.non_error_files }}
+          to: ${{ steps.error_info.outputs.commit_author_email }}
+          from: ${{ secrets.GMAIL_USERNAME }}
+          attachments: build_errors.log
 
   send_success_notification:
-              name: Send Success Notification
-              runs-on: ubuntu-latest
-              needs: [lint, build,ZAP_API_Scan_Before ]
-              if: ${{ success() }}
-              concurrency:
-                group: send-success-notification-${{ github.ref }}
-                cancel-in-progress: false
-              steps:
-                - name: Checkout Code
-                  uses: actions/checkout@v3
-                  with:
-                    fetch-depth: 0  # Fetch all history
+    name: Send Success Notification
+    runs-on: ubuntu-latest
+    needs: [
+        dependabot,
+        lint,
+        build,
+        # run-web-and-test,
+        # ZAP_Full_Scan_Before,
+        ZAP_API_Scan_Before,
+      ]
+    if: ${{ success() }}
+    concurrency:
+      group: send-success-notification-${{ github.ref }}
+      cancel-in-progress: false
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch all history
 
-                - name: Get Commit Info
-                  id: commit_info
-                  run: |
-                    # Get the author information from the latest commit
-                    COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%ae')
-
-                    if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
-                      COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)')
-                    fi
-
-                    changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-                    echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
-                    echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
-
-                - name: Send email on success
-                  uses: dawidd6/action-send-mail@v3
-                  with:
-                    server_address: smtp.gmail.com
-                    server_port: 587
-                    username: ${{ secrets.GMAIL_USERNAME }}
-                    password: ${{ secrets.GMAIL_APP_PASSWORD }}
-                    subject: "Build success for ${{ github.repository }}"
-                    body: |
-                      Build succeeded for commit: ${{ github.sha }}
-
-                      Files changed: ${{ steps.commit_info.outputs.changed_files }}
-
-                    to: ${{ steps.commit_info.outputs.commit_author_email }}
-                    from: ${{ secrets.GMAIL_USERNAME }}
+      - name: Get Commit Info
+        id: commit_info
+        run: |
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%ae')
+          if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)' || true)
+          fi
+          if [ -z "$COMMIT_AUTHOR_EMAIL" ]; then
+            COMMIT_AUTHOR_EMAIL="default@example.com" # เพิ่มค่า default email หากไม่มีข้อมูล
+          fi
+          if git diff --quiet HEAD~1 HEAD; then
+            changed_files=""
+          else
+            changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
+          fi
+          echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
+          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
+      - name: Send email on success
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.GMAIL_USERNAME }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          subject: "Build success for ${{ github.repository }}"
+          body: |
+            Build succeeded for commit: ${{ github.sha }}
+            Files changed: ${{ steps.commit_info.outputs.changed_files }}
+          to: ${{ steps.commit_info.outputs.commit_author_email || secrets.DEFAULT_EMAIL }}
+          from: ${{ secrets.GMAIL_USERNAME }}
