2345

diff --git a/.github/workflows/fateone.yml b/.github/workflows/fateone.yml
--- a/.github/workflows/fateone.yml
+++ b/.github/workflows/fateone.yml
@@ -78,7 +78,7 @@ jobs:
       - name: Build Project
         id: build
         run: |
-          npm run build 2> build_errors.log || true
+          npm run build 2> error-files || true
           exit_code=$?
           echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
           exit $exit_code
@@ -87,7 +87,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: error-files
-          path: build_errors.log
+          path: error-files
 
   # run-web-and-test:
   #   name: Run Web and Playwright Tests
@@ -222,16 +222,17 @@ jobs:
             COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
           fi
           changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-          error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
+          error_paths=$(grep -o '/.*error' error-files | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
           echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
           non_error_files=""
           for file in $changed_files; do
-            if ! grep -q "$file" build_errors.log; then
+            if ! grep -q "$file" error-files; then
               non_error_files+="$file "
             fi
           done
           echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
           echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
+
       - name: Send email on failure
         uses: dawidd6/action-send-mail@v3
         with:
@@ -247,7 +248,7 @@ jobs:
             Files changed: ${{ steps.error_info.outputs.non_error_files }}
           to: ${{ steps.error_info.outputs.commit_author_email }}
           from: ${{ secrets.GMAIL_USERNAME }}
-          attachments: build_errors.log
+          attachments: error-files
 
   send_success_notification:
     name: Send Success Notification
