uhr45jwae

diff --git a/.github/workflows/fateone.yml b/.github/workflows/fateone.yml
--- a/.github/workflows/fateone.yml
+++ b/.github/workflows/fateone.yml
@@ -218,18 +218,23 @@ jobs:
         run: |
           # Get the author information from the latest commit
           COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
+
           if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
             COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
           fi
+
           changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-          error_paths=$(grep -o '/.*error' error-files | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
+
+          error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
           echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
+
           non_error_files=""
           for file in $changed_files; do
-            if ! grep -q "$file" error-files; then
+            if ! grep -q "$file" build_errors.log; then
               non_error_files+="$file "
             fi
           done
+
           echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
           echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
 
@@ -243,12 +248,15 @@ jobs:
           subject: "Build failure for ${{ github.repository }}"
           body: |
             Build failed for commit: ${{ github.sha }}
+
             Files with errors:
             ${{ steps.error_info.outputs.error_paths }}
+
             Files changed: ${{ steps.error_info.outputs.non_error_files }}
+
           to: ${{ steps.error_info.outputs.commit_author_email }}
           from: ${{ secrets.GMAIL_USERNAME }}
-          attachments: error-files
+          attachments: build_errors.log
 
   send_success_notification:
     name: Send Success Notification
