หกดหกดหกด

diff --git a/.github/workflows/fateone.yml b/.github/workflows/fateone.yml
--- a/.github/workflows/fateone.yml
+++ b/.github/workflows/fateone.yml
@@ -82,6 +82,7 @@ jobs:
           exit_code=$?
           echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
           exit $exit_code
+
       - name: Upload Error Files
         if: ${{ env.error_files_present == 'true' || always() }}
         uses: actions/upload-artifact@v3
@@ -216,6 +217,7 @@ jobs:
       - name: Get Error Log and Commit Info
         id: error_info
         run: |
+          set -e
           # Get the author information from the latest commit
           COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
 
@@ -224,12 +226,12 @@ jobs:
           fi
 
           # Check if build_errors.log exists before processing it
-          if [[ -f build_errors.log ]]; then
-            error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
-          else
-            echo "build_errors.log not found." >> $GITHUB_OUTPUT
-            error_paths=""
+          if [[ ! -f build_errors.log ]]; then
+            echo "Error: build_errors.log not found."
+            exit 1
           fi
+
+          error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
           echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
 
           changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
