scasdcas

diff --git a/.github/workflows/fateone.yml b/.github/workflows/fateone.yml
--- a/.github/workflows/fateone.yml
+++ b/.github/workflows/fateone.yml
@@ -90,225 +90,217 @@ jobs:
           name: error-files
           path: build_errors.log
 
-  run-web-and-test:
-    name: Run Web and Playwright Tests
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # run-web-and-test:
+  #   name: Run Web and Playwright Tests
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: "16.20.2"
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v2
+  #       with:
+  #         node-version: "16.20.2"
 
-      - name: Set npm registry
-        run: npm config set registry https://registry.npmjs.org/
+  #     - name: Set npm registry
+  #       run: npm config set registry https://registry.npmjs.org/
 
-      - name: Install dependencies
-        run: npm install --legacy-peer-deps
+  #     - name: Install dependencies
+  #       run: npm install --legacy-peer-deps
 
-      - name: Start the app
-        run: |
-          npm start &
-          npx wait-on http://localhost:4200
-        env:
-          PORT: 4200
+  #     - name: Start the app
+  #       run: |
+  #         npm start &
+  #         npx wait-on http://localhost:4200
+  #       env:
+  #         PORT: 4200
 
-      - name: Install Playwright
-        run: npx playwright install
+  #     - name: Install Playwright
+  #       run: npx playwright install
 
-      - name: Run Playwright tests
-        run: npx playwright test
+  #     - name: Run Playwright tests
+  #       run: npx playwright test
 
-      - name: Create screenshots directory
-        if: always()
-        run: mkdir -p screenshots
+  #     - name: Create screenshots directory
+  #       if: always()
+  #       run: mkdir -p screenshots
 
-      - name: Upload Screenshots
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: playwright-screenshots
-          path: screenshots/failure.png
+  #     - name: Upload Screenshots
+  #       if: always()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: playwright-screenshots
+  #         path: screenshots/failure.png
 
-  ZAP_Full_Scan_Before:
-    runs-on: ubuntu-latest
-    needs: run-web-and-test
-    name: ZAP_Full_Scan_Before
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          ref: master
+  # ZAP_Full_Scan_Before:
+  #   runs-on: ubuntu-latest
+  #   needs: run-web-and-test
+  #   name: ZAP_Full_Scan_Before
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: master
 
-      - name: ZAP Scan
-        uses: zaproxy/action-full-scan@v0.11.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
-          target: "https://24d95ca73e89dfa76c417797f94624e1.serveo.net/" #ลิ้งของ pea แบบ public
-          cmd_options: "-a"
+  #     - name: ZAP Scan
+  #       uses: zaproxy/action-full-scan@v0.11.0
+  #       with:
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         docker_name: "ghcr.io/zaproxy/zaproxy:stable"
+  #         target: "https://24d95ca73e89dfa76c417797f94624e1.serveo.net/" #ลิ้งของ pea แบบ public
+  #         cmd_options: "-a"
 
-      - name: Upload ZAP Scan Report
-        uses: actions/upload-artifact@v3
-        with:
-          name: ZAP_Full_Scan_Before
-          path: |
-            report_json.json
-            report_md.md
-            report_html.html
+  #     - name: Upload ZAP Scan Report
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ZAP_Full_Scan_Before
+  #         path: |
+  #           report_json.json
+  #           report_md.md
+  #           report_html.html
 
-  ZAP_API_Scan_Before:
-    runs-on: ubuntu-latest
-    needs: run-web-and-test
-    name: ZAP_API_Scan_Before
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          ref: master
+  # ZAP_API_Scan_Before:
+  #   runs-on: ubuntu-latest
+  #   needs: run-web-and-test
+  #   name: ZAP_API_Scan_Before
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: master
 
-      - name: ZAP Scan
-        uses: zaproxy/action-api-scan@v0.8.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
-          format: openapi
-          target: "https://24d95ca73e89dfa76c417797f94624e1.serveo.net/" #ลิ้งของ pea แบบ public
-          cmd_options: "-a"
+  #     - name: ZAP Scan
+  #       uses: zaproxy/action-api-scan@v0.8.0
+  #       with:
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         docker_name: "ghcr.io/zaproxy/zaproxy:stable"
+  #         format: openapi
+  #         target: "https://24d95ca73e89dfa76c417797f94624e1.serveo.net/" #ลิ้งของ pea แบบ public
+  #         cmd_options: "-a"
 
-      - name: Upload ZAP Scan Report
-        uses: actions/upload-artifact@v3
-        with:
-          name: ZAP_API_Scan_Before
-          path: |
-            report_json.json
-            report_md.md
-            report_html.html
+  #     - name: Upload ZAP Scan Report
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ZAP_API_Scan_Before
+  #         path: |
+  #           report_json.json
+  #           report_md.md
+  #           report_html.html
 
   send_failure_notification:
-              name: Send Failure Notification
-              runs-on: ubuntu-latest
-              needs:
-                [
-                  dependabot,
-                  lint,
-                  build,
-                  run-web-and-test,
-                  ZAP_Full_Scan_Before,
-                  ZAP_API_Scan_Before,
+    name: Send Failure Notification
+    runs-on: ubuntu-latest
+    needs:
+      [
+        dependabot,
+        lint,
+        build,
+        # run-web-and-test,
+        # ZAP_Full_Scan_Before,
+        # ZAP_API_Scan_Before,
+      ]
+    if: ${{ failure() }}
+    concurrency:
+      group: send-failure-notification-${{ github.ref }}
+      cancel-in-progress: false
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch all history
 
-                ]
-              if: ${{ failure() }}
-              concurrency:
-                group: send-failure-notification-${{ github.ref }}
-                cancel-in-progress: false
-              steps:
-                - name: Checkout Code
-                  uses: actions/checkout@v3
-                  with:
-                    fetch-depth: 0 # Fetch all history
+      - name: Download Error Files
+        uses: actions/download-artifact@v3
+        with:
+          name: error-files
 
-                - name: Download Error Files
-                  uses: actions/download-artifact@v3
-                  with:
-                    name: error-files
-
-                - name: Get Error Log and Commit Info
-                  id: error_info
-                  run: |
-                    # Get the author information from the latest commit
-                    COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
-
-                    if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
-                      COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
-                    fi
-
-                    changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-
-                    error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
-                    echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
-
-                    non_error_files=""
-                    for file in $changed_files; do
-                      if ! grep -q "$file" build_errors.log; then
-                        non_error_files+="$file "
-                      fi
-                    done
-
-                    echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
-                    echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
-
-                - name: Send email on failure
-                  uses: dawidd6/action-send-mail@v3
-                  with:
-                    server_address: smtp.gmail.com
-                    server_port: 587
-                    username: ${{ secrets.GMAIL_USERNAME }}
-                    password: ${{ secrets.GMAIL_APP_PASSWORD }}
-                    subject: "Build failure for ${{ github.repository }}"
-                    body: |
-                      Build failed for commit: ${{ github.sha }}
-
-                      Files with errors:
-                      ${{ steps.error_info.outputs.error_paths }}
-
-                      Files changed: ${{ steps.error_info.outputs.non_error_files }}
-
-                    to: ${{ steps.error_info.outputs.commit_author_email }}
-                    from: ${{ secrets.GMAIL_USERNAME }}
-                    attachments: build_errors.log
+      - name: Get Error Log and Commit Info
+        id: error_info
+        run: |
+          # Get the author information from the latest commit
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
+          if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
+          fi
+          changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
+          error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
+          echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
+          non_error_files=""
+          for file in $changed_files; do
+            if ! grep -q "$file" build_errors.log; then
+              non_error_files+="$file "
+            fi
+          done
+          echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
+          echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
+      - name: Send email on failure
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.GMAIL_USERNAME }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          subject: "Build failure for ${{ github.repository }}"
+          body: |
+            Build failed for commit: ${{ github.sha }}
+            Files with errors:
+            ${{ steps.error_info.outputs.error_paths }}
+            Files changed: ${{ steps.error_info.outputs.non_error_files }}
+          to: ${{ steps.commit_info.outputs.commit_author_email || secrets.DEFAULT_EMAIL }}
+          from: ${{ secrets.GMAIL_USERNAME }}
+          attachments: build_errors.log
 
   send_success_notification:
-              name: Send Success Notification
-              runs-on: ubuntu-latest
-              needs:
-                [
-                  dependabot,
-                  lint,
-                  build,
-                  run-web-and-test,
-                  ZAP_Full_Scan_Before,
-                  ZAP_API_Scan_Before,
-                ]
-              if: ${{ success() }}
-              concurrency:
-                group: send-success-notification-${{ github.ref }}
-                cancel-in-progress: false
-              steps:
-                - name: Checkout Code
-                  uses: actions/checkout@v3
-                  with:
-                    fetch-depth: 0 # Fetch all history
+    name: Send Success Notification
+    runs-on: ubuntu-latest
+    needs:
+      [
+        dependabot,
+        lint,
+        build,
+        # run-web-and-test,
+        # ZAP_Full_Scan_Before,
+        # ZAP_API_Scan_Before,
+      ]
+    if: ${{ success() }}
+    concurrency:
+      group: send-success-notification-${{ github.ref }}
+      cancel-in-progress: false
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch all history
 
-                - name: Get Commit Info
-                  id: commit_info
-                  run: |
-                    # Get the author information from the latest commit
-                    COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%ae')
+      - name: Get Commit Info
+        id: commit_info
+        run: |
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%ae')
+          if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)' || true)
+          fi
+          if [ -z "$COMMIT_AUTHOR_EMAIL" ]; then
+            COMMIT_AUTHOR_EMAIL="default@example.com" # เพิ่มค่า default email หากไม่มีข้อมูล
+          fi
+          if git diff --quiet HEAD~1 HEAD; then
+            changed_files=""
+          else
+            changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
+          fi
+          echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
+          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
 
-                    if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
-                      COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)')
-                    fi
-
-                    changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-                    echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
-                    echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
-
-                - name: Send email on success
-                  uses: dawidd6/action-send-mail@v3
-                  with:
-                    server_address: smtp.gmail.com
-                    server_port: 587
-                    username: ${{ secrets.GMAIL_USERNAME }}
-                    password: ${{ secrets.GMAIL_APP_PASSWORD }}
-                    subject: "Build success for ${{ github.repository }}"
-                    body: |
-                      Build succeeded for commit: ${{ github.sha }}
-
-                      Files changed: ${{ steps.commit_info.outputs.changed_files }}
-
-                    to: ${{ steps.commit_info.outputs.commit_author_email }}
-                    from: ${{ secrets.GMAIL_USERNAME }}
+      - name: Send email on success
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.GMAIL_USERNAME }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          subject: "Build success for ${{ github.repository }}"
+          body: |
+            Build succeeded for commit: ${{ github.sha }}
+            Files changed: ${{ steps.commit_info.outputs.changed_files }}
+          to: ${{ steps.commit_info.outputs.commit_author_email || secrets.DEFAULT_EMAIL }}
+          from: ${{ secrets.GMAIL_USERNAME }}
