Main

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -117,44 +117,53 @@ jobs:
     name: Run Web and Playwright Tests
     runs-on: ubuntu-latest
     needs: run-api
+
     steps:
-    - name: Checkout Web repository
-      uses: actions/checkout@v3
-      with:
-        repository: Lefisius/PresidentDemo-Web
-        token: ${{ secrets.GH_PAT }}
-        ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
+      - name: Checkout Web repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-Web
+          token: ${{ secrets.GH_PAT }}
+          ref: ${{ github.event.inputs.web_branch || 'main' }}
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '16.20.2'
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
 
-    - name: Set npm registry
-      run: npm config set registry https://registry.npmjs.org/
+      - name: Set npm registry
+        run: npm config set registry https://registry.npmjs.org/
 
-    - name: Install dependencies
-      run: npm install --force
+      - name: Install dependencies
+        run: npm install --force
 
-    - name: Start the app
-      run: |
-        npm start &
-        npx wait-on http://localhost:4200
-      env:
-        PORT: 4200
+      - name: Start the app
+        run: |
+          npm start &
+          npx wait-on http://localhost:4200
+        env:
+          PORT: 4200
 
-    - name: Install Playwright
-      run: npx playwright install
+      - name: Install Playwright
+        run: npx playwright install
 
-    - name: Run Playwright tests
-      id: run-tests
-      run: npx playwright test president/E2E-Script --reporter=json --output=playwright-report || true
+      - name: Run Playwright tests
+        id: run-tests
+        run: |
+          npx playwright test --output=results.json || exit 1
+          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+            echo "Tests failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
 
-    - name: Upload Playwright test results
-      uses: actions/upload-artifact@v3
-      with:
-        name: playwright-results
-        path: playwright-report/
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: playwright-results
+          path: results.json
 
   # push_to_registry:
   #   name: Push Docker image to Docker Hub
