main

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -57,41 +57,48 @@ jobs:
   #         VALIDATE_ALL_CODEBASE: false
   #         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
 
-  build:
-    name: Build Project
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+  # build:
+  #   name: Build Project
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: "16.20.2"
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v2
+  #       with:
+  #         node-version: "16.20.2"
 
-      - name: Install dependencies
-        run: npm install --legacy-peer-deps
+  #     - name: Install dependencies
+  #       run: npm install --legacy-peer-deps
 
-      - name: Build Project
-        id: build
-        run: |
-          npm run build 2> build_errors.log || true
-          exit_code=$?
-          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
-          exit $exit_code
+  #     - name: Build Project
+  #       id: build
+  #       run: |
+  #         npm run build 2> build_errors.log || true
+  #         exit_code=$?
+  #         echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
+  #         exit $exit_code
 
-      - name: Upload Error Files
-        if: ${{ env.error_files_present == 'true' || always() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: error-files
-          path: build_errors.log
+  #     - name: Upload Error Files
+  #       if: ${{ env.error_files_present == 'true' || always() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: error-files
+  #         path: build_errors.log
 
   run-web-and-test:
     name: Run Web and Playwright Tests
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Checkout Web repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-Web
+          token: ${{ secrets.GH_PAT }}
+          ref: ${{ github.event.inputs.web_branch || 'main' }}
+
       - name: Checkout code
         uses: actions/checkout@v2
 
