zap new

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -113,45 +113,50 @@ jobs:
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
 
-  zap_scan:
-    name: OWASP ZAP Scan
-    runs-on: ubuntu-latest
-    needs: push_to_registry
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+zap_scan:
+  name: OWASP ZAP Scan
+  runs-on: ubuntu-latest
+  needs: push_to_registry
+  steps:
+    - name: Checkout Code
+      uses: actions/checkout@v3
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16.20.2'
+    - name: Set up Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '16.20.2'
 
-      - name: Install dependencies
-        run: npm install --legacy-peer-deps
+    - name: Install dependencies
+      run: npm install --legacy-peer-deps
 
-      - name: Start Angular App
-        run: |
-          nohup ng serve --port 4200 --host 0.0.0.0 &> angular.log &
-          sleep 60
+    - name: Start Angular App
+      run: |
+        nohup ng serve --port 4200 --host 0.0.0.0 &> angular.log &
+        sleep 60
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Check if ZAP reports exist
-        run: |
-          if [ ! -f zap-report.log ]; then
-            echo "zap-report.log not found!"
-            exit 1
-          fi
+    - name: Run OWASP ZAP Scan
+      run: |
+        docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:4200 -r zap-report.log -J zap-report.json
+      sleep 60
 
-      - name: Upload ZAP Logs
-        uses: actions/upload-artifact@v3
-        with:
-          name: zap-logs
-          path: zap-report.log
+    - name: Check if ZAP log exists
+      run: |
+        if [ ! -f zap-report.log ]; then
+          echo "zap-report.log not found!"
+          exit 1
+        fi
+
+    - name: Upload ZAP Log
+      uses: actions/upload-artifact@v3
+      with:
+        name: zap-log
+        path: zap-report.log
 
   trigger_jenkins:
     name: Trigger Jenkins Job
