zapjar

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -95,25 +95,31 @@ jobs:
     runs-on: ubuntu-latest
     needs: push_to_registry
     steps:
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Run ZAP scan inside image
+      - name: Start Docker container
         run: |
-          docker run --rm lefisius/dockerbuild \
-          java -jar /zap/zap_files/zap.jar -cmd -quickurl http://localhost:80/ -r /zap/zap_report.html
+          docker run -d --name my-container -p 80:80 lefisius/dockerbuild
+
+      - name: Verify ZAP installation
+        run: |
+          docker exec my-container ls /zap/zap_files
+
+      - name: Run ZAP scan
+        run: |
+          if docker exec my-container java -jar /zap/zap_files/zap.jar -cmd -quickurl http://localhost:80/ -r /zap/zap_report.html; then
+            echo "ZAP Scan completed successfully"
+          else
+            echo "ZAP Scan failed"
+            exit 1
+          fi
+        shell: bash
         env:
           ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
 
-      - name: Upload ZAP Report
-        uses: actions/upload-artifact@v3
-        with:
-          name: zap_report
-          path: /zap/zap_report.html
-
+      - name: Stop and remove Docker container
+        if: always()
+        run: |
+          docker stop my-container
+          docker rm my-container
 
   trigger_jenkins:
     name: Trigger Jenkins Job
