ss

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -12,6 +12,7 @@ jobs:
   dependabot:
     name: Dependabot Updates
     runs-on: ubuntu-latest
+    if: false
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -42,6 +43,7 @@ jobs:
   lint:
     name: Lint Code Base
     runs-on: ubuntu-latest
+    if: false
     needs: dependabot
     steps:
       - name: Checkout Code
@@ -56,6 +58,7 @@ jobs:
   build:
     name: Build Project
     runs-on: ubuntu-latest
+    if: false
     needs: lint
     steps:
       - name: Checkout Code
@@ -87,6 +90,7 @@ jobs:
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
+    if: false
     needs: build
     steps:
       - name: Checkout Code
@@ -140,17 +144,23 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Run OWASP ZAP
+      - name: Check if ZAP reports exist
         run: |
-          docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
-          -t http://localhost:4200/ -g zap-report.log -r zap-report.html || true
-          
+          if [ ! -f zap-report.log ]; then
+            echo "zap-report.log not found!"
+            exit 1
+          fi
+          if [ ! -f zap-report.html ]; then
+            echo "zap-report.html not found!"
+            exit 1
+          fi
+
       - name: Upload ZAP Logs
         uses: actions/upload-artifact@v3
         with:
           name: zap-logs
           path: zap-report.log
-          
+
       - name: Upload ZAP Report
         uses: actions/upload-artifact@v3
         with:
@@ -160,6 +170,7 @@ jobs:
   trigger_jenkins:
     name: Trigger Jenkins Job
     runs-on: ubuntu-latest
+    if: false
     needs: zap_scan
     steps:
       - name: Trigger Jenkins Job
@@ -170,6 +181,7 @@ jobs:
   get_commit_author_email:
     name: Get Commit Author Email
     runs-on: ubuntu-latest
+    if: false
     outputs:
       commit_author_email: ${{ steps.get_commit_info.outputs.commit_author_email }}
       changed_files: ${{ steps.get_commit_info.outputs.changed_files }}
@@ -190,6 +202,7 @@ jobs:
   send_failure_notification:
     name: Send Failure Notification
     runs-on: ubuntu-latest
+    if: false
     needs: [dependabot, lint, build, push_to_registry, zap_scan, trigger_jenkins]
     if: ${{ failure() }}
     steps:
@@ -256,6 +269,7 @@ jobs:
   send_success_notification:
     name: Send Success Notification
     runs-on: ubuntu-latest
+    if: false
     needs: [dependabot, lint, build, push_to_registry, zap_scan, trigger_jenkins]
     if: ${{ always() }}
     steps:
