e2e

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -8,6 +8,19 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch:
+    inputs:
+      api_branch:
+        description: "API branch to checkout"
+        required: true
+        default: "main"
+      web_branch:
+        description: "Web branch to checkout"
+        required: true
+        default: "main"
 
 jobs:
   dependabot:
@@ -75,6 +88,82 @@ jobs:
           name: error-files
           path: build_errors.log
 
+    # Run API Job from Run API, Web, and Playwright Tests workflow
+  run-api:
+    name: Run API
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Checkout API repository
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.inputs.api_branch || 'main' }}
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          distribution: "adopt"
+          java-version: "17"
+
+      - name: Build and Run Spring Boot API
+        run: |
+          mvn clean install
+          nohup mvn spring-boot:run > /dev/null 2>&1 &
+
+  # Run Web and Playwright Tests Job from Run API, Web, and Playwright Tests workflow
+  run-web-and-test:
+    name: Run Web and Playwright Tests
+    runs-on: ubuntu-latest
+    needs: run-api
+
+    steps:
+      - name: Checkout Web repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-Web
+          token: ${{ secrets.GH_PAT }}
+          ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+
+      - name: Set npm registry
+        run: npm config set registry https://registry.npmjs.org/
+
+      - name: Install dependencies
+        run: npm install --force
+
+      - name: Start the app
+        run: |
+          npm start &
+          npx wait-on http://localhost:4200
+        env:
+          PORT: 4200
+
+      - name: Install Playwright
+        run: npx playwright install
+
+      - name: Run Playwright tests
+        id: run-tests
+        run: |
+          npx playwright test --output=results.json || exit 1
+          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+            echo "Tests failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: playwright-results
+          path: results.json
+
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
@@ -120,36 +209,36 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
-          fetch-depth: 0  # Fetch all history for all branches and tags
+          fetch-depth: 0 # Fetch all history for all branches and tags
 
       - name: Create New Branch with Commit Message
         env:
           GH_PAT: ${{ secrets.GH_PAT }}
         run: |
-            # Get the author information from the latest commit
-            COMMIT_AUTHOR_NAME=$(git log -1 --pretty=%an)
-            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
+          # Get the author information from the latest commit
+          COMMIT_AUTHOR_NAME=$(git log -1 --pretty=%an)
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
 
-            # Set the git config to use the author's info
-            git config user.name "$COMMIT_AUTHOR_NAME"
-            git config user.email "$COMMIT_AUTHOR_EMAIL"
+          # Set the git config to use the author's info
+          git config user.name "$COMMIT_AUTHOR_NAME"
+          git config user.email "$COMMIT_AUTHOR_EMAIL"
 
-            FULL_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+          FULL_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
 
-            if [[ $FULL_COMMIT_MESSAGE == Merge\ pull\ request* ]]; then
-              PR_NUM=$(echo "$FULL_COMMIT_MESSAGE" | grep -oP '#\K\d+')
-              PR_TITLE=$(git log -1 --pretty=%B | sed -n '5p' | cut -c1-50)
-              COMMIT_MESSAGE="pr-${PR_NUM}-${PR_TITLE}"
-            else
-              COMMIT_MESSAGE=$(echo "$FULL_COMMIT_MESSAGE" | head -n 1)
-            fi
+          if [[ $FULL_COMMIT_MESSAGE == Merge\ pull\ request* ]]; then
+            PR_NUM=$(echo "$FULL_COMMIT_MESSAGE" | grep -oP '#\K\d+')
+            PR_TITLE=$(git log -1 --pretty=%B | sed -n '5p' | cut -c1-50)
+            COMMIT_MESSAGE="pr-${PR_NUM}-${PR_TITLE}"
+          else
+            COMMIT_MESSAGE=$(echo "$FULL_COMMIT_MESSAGE" | head -n 1)
+          fi
 
-            SANITIZED_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '-' | sed 's/^-//;s/-$//' | cut -c1-50)
+          SANITIZED_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '-' | sed 's/^-//;s/-$//' | cut -c1-50)
 
-            NEW_BRANCH_NAME="log-${SANITIZED_MESSAGE}"
+          NEW_BRANCH_NAME="log-${SANITIZED_MESSAGE}"
 
-            git checkout -b $NEW_BRANCH_NAME
-            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
+          git checkout -b $NEW_BRANCH_NAME
+          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
 
   ZAP_Full_Scan:
     runs-on: ubuntu-latest
