newcode test

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -144,7 +144,14 @@ jobs:
           docker run --rm -v ${{ github.workspace }}/output:/output lefisius/dockerbuild:main \
             java -jar /zap/ZAP_D-2024-09-17/zap-D-2024-09-17.jar -cmd \
             -quickurl https://acec-61-7-146-25.ngrok-free.app/ \
-            -quickout /output/zap_report.html
+            -quickout /output/zap_report.html || { echo "ZAP scan failed"; exit 1; }
+      
+      - name: Verify report generation
+        run: |
+          if [ ! -f ./output/zap_report.html ]; then
+            echo "ZAP report was not generated!"
+            exit 1
+          fi
 
       - name: Check output directory
         run: ls -l output
