mergi pipeline

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -8,6 +8,19 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch:
+    inputs:
+      api_branch:
+        description: 'API branch to checkout'
+        required: true
+        default: 'main'
+      web_branch:
+        description: 'Web branch to checkout'
+        required: true
+        default: 'main'
 
 jobs:
   dependabot:
@@ -75,10 +88,86 @@ jobs:
           name: error-files
           path: build_errors.log
 
+  # Run API Job
+  run-api:
+    name: Run API
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout API repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-API
+          ref: ${{ github.event.inputs.api_branch || 'main' }}
+          token: ${{ secrets.GH_PAT }}
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '17'
+
+      - name: Build and Run Spring Boot API
+        run: |
+          mvn clean install
+          nohup mvn spring-boot:run > /dev/null 2>&1 &
+
+  # Run Web and Playwright Tests Job
+  run-web-and-test:
+    name: Run Web and Playwright Tests
+    runs-on: ubuntu-latest
+    needs: run-api
+    steps:
+      - name: Checkout Web repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-Web
+          token: ${{ secrets.GH_PAT }}
+          ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+
+      - name: Set npm registry
+        run: npm config set registry https://registry.npmjs.org/
+
+      - name: Install dependencies
+        run: npm install --force
+
+      - name: Start the app
+        run: |
+          npm start &
+          npx wait-on http://localhost:4200
+        env:
+          PORT: 4200
+
+      - name: Install Playwright
+        run: npx playwright install
+
+      - name: Run Playwright tests
+        id: run-tests
+        run: |
+          npx playwright test --output=results.json || exit 1
+          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+            echo "Tests failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: playwright-results
+          path: results.json
+
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
-    needs: build
+    needs: run-web-and-test
     concurrency:
       group: push-to-registry-${{ github.ref }}
       cancel-in-progress: false
@@ -273,6 +362,8 @@ jobs:
         dependabot,
         lint,
         build,
+        run-api,
+        run-web-and-test,
         push_to_registry,
         ZAP_Full_Scan,
         ZAP_API_Scan,
@@ -346,6 +437,8 @@ jobs:
         dependabot,
         lint,
         build,
+        run-api,
+        run-web-and-test,
         push_to_registry,
         ZAP_Full_Scan,
         ZAP_API_Scan,
