555

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -89,85 +89,86 @@ jobs:
           path: build_errors.log
 
   # Run API Job
-  run-api:
-    name: Run API
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout API repository
-        uses: actions/checkout@v3
-        with:
-          repository: Theerapat-dev/PresidentDemo-API
-          ref: ${{ github.event.inputs.api_branch || 'main' }}
-          token: ${{ secrets.GH_PAT }}
+  # run-api:
+  #   name: Run API
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - name: Checkout API repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: Theerapat-dev/PresidentDemo-API
+  #         ref: ${{ github.event.inputs.api_branch || 'main' }}
+  #         token: ${{ secrets.GH_PAT }}
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '17'
+  #     - name: Set up JDK 17
+  #       uses: actions/setup-java@v2
+  #       with:
+  #         distribution: 'adopt'
+  #         java-version: '17'
 
-      - name: Build and Run Spring Boot API
-        run: |
-          mvn clean install
-          nohup mvn spring-boot:run > /dev/null 2>&1 &
+  #     - name: Build and Run Spring Boot API
+  #       run: |
+  #         mvn clean install
+  #         nohup mvn spring-boot:run > /dev/null 2>&1 &
 
   # Run Web and Playwright Tests Job
-  run-web-and-test:
-    name: Run Web and Playwright Tests
-    runs-on: ubuntu-latest
-    needs: run-api
-    steps:
-      - name: Checkout Web repository
-        uses: actions/checkout@v3
-        with:
-          repository: Lefisius/PresidentDemo-Web
-          token: ${{ secrets.GH_PAT }}
-          ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
+  # run-web-and-test:
+  #   name: Run Web and Playwright Tests
+  #   runs-on: ubuntu-latest
+  #   needs: run-api
+  #   steps:
+  #     - name: Checkout Web repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: Lefisius/PresidentDemo-Web
+  #         token: ${{ secrets.GH_PAT }}
+  #         ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '16'
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '16'
 
-      - name: Set npm registry
-        run: npm config set registry https://registry.npmjs.org/
+  #     - name: Set npm registry
+  #       run: npm config set registry https://registry.npmjs.org/
 
-      - name: Install dependencies
-        run: npm install --force
+  #     - name: Install dependencies
+  #       run: npm install --force
 
-      - name: Start the app
-        run: |
-          npm start &
-          npx wait-on http://localhost:4200
-        env:
-          PORT: 4200
+  #     - name: Start the app
+  #       run: |
+  #         npm start &
+  #         npx wait-on http://localhost:4200
+  #       env:
+  #         PORT: 4200
 
-      - name: Install Playwright
-        run: npx playwright install
+  #     - name: Install Playwright
+  #       run: npx playwright install
 
-      - name: Run Playwright tests
-        id: run-tests
-        run: |
-          npx playwright test --output=results.json || exit 1
-          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
-            echo "Tests failed."
-            exit 1
-          else
-            echo "Tests passed."
-          fi
+  #     - name: Run Playwright tests
+  #       id: run-tests
+  #       run: |
+  #         npx playwright test --output=results.json || exit 1
+  #         if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+  #           echo "Tests failed."
+  #           exit 1
+  #         else
+  #           echo "Tests passed."
+  #         fi
 
-      - name: Upload test results
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: playwright-results
-          path: results.json
+  #     - name: Upload test results
+  #       if: always()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: playwright-results
+  #         path: results.json
 
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
-    needs: run-web-and-test
+    # needs: run-web-and-test
+    needs: build
     concurrency:
       group: push-to-registry-${{ github.ref }}
       cancel-in-progress: false
@@ -255,7 +256,7 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           docker_name: "ghcr.io/zaproxy/zaproxy:stable"
-          target: "https://2146-61-7-146-25.ngrok-free.app/"
+          target: "https://929d2ec45279452016e377e368c5d296.serveo.net/"
           cmd_options: "-a"
 
   ZAP_API_Scan:
@@ -274,7 +275,7 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           docker_name: "ghcr.io/zaproxy/zaproxy:stable"
           format: openapi
-          target: "https://2146-61-7-146-25.ngrok-free.app/"
+          target: "https://929d2ec45279452016e377e368c5d296.serveo.net/"
           cmd_options: "-a"
 
       - name: Upload ZAP Scan Report
@@ -302,7 +303,7 @@ jobs:
       - name: Trigger Jenkins Job
         id: trigger_jenkins
         run: |
-          response=$(curl -X POST "https://173ef3c10936cbcf87fa20a2274f4915.serveo.net/job/testpipe/build" \
+          response=$(curl -X POST "https://078ff72c07d6d7bd2ebde5529f23f831.serveo.net/job/testpipe/build" \
           --user "user:11b20d5f21817203f0fb4db12e13b2402e")
           echo "Triggered Jenkins Job"
 
@@ -314,7 +315,7 @@ jobs:
           while [ "$job_status" != "SUCCESS" ] && [ $attempt -lt $max_attempts ]; do
             sleep 15
             attempt=$((attempt+1))
-            response=$(curl -s -w "%{http_code}" "https://173ef3c10936cbcf87fa20a2274f4915.serveo.net/job/testpipe/lastBuild/api/json" \
+            response=$(curl -s -w "%{http_code}" "https://078ff72c07d6d7bd2ebde5529f23f831.serveo.net/job/testpipe/lastBuild/api/json" \
               --user "user:11b20d5f21817203f0fb4db12e13b2402e")
             http_code=${response: -3}
             body=${response:0:${#response}-3}
@@ -362,8 +363,8 @@ jobs:
         dependabot,
         lint,
         build,
-        run-api,
-        run-web-and-test,
+        # run-api,
+        # run-web-and-test,
         push_to_registry,
         ZAP_Full_Scan,
         ZAP_API_Scan,
@@ -437,8 +438,8 @@ jobs:
         dependabot,
         lint,
         build,
-        run-api,
-        run-web-and-test,
+        # run-api,
+        # run-web-and-test,
         push_to_registry,
         ZAP_Full_Scan,
         ZAP_API_Scan,
@@ -483,4 +484,3 @@ jobs:
 
           to: ${{ steps.commit_info.outputs.commit_author_email }}
           from: ${{ secrets.GMAIL_USERNAME }}
-          
