เเเเเเเ

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -9,47 +9,8 @@ on:
       - main
 
 jobs:
-  # push_to_registry:
-  #   name: Push Docker image to Docker Hub
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check out the repo
-  #       uses: actions/checkout@v3
-
-  #     - name: Log in to Docker Hub
-  #       uses: docker/login-action@v2
-  #       with:
-  #         username: ${{ secrets.DOCKER_USERNAME }}
-  #         password: ${{ secrets.DOCKER_PASSWORD }}
-
-  #     - name: Extract metadata for Docker
-  #       id: meta
-  #       uses: docker/metadata-action@v4
-  #       with:
-  #         images: lefisius/dockerbuild
-
-  #     - name: Build and push Docker image
-  #       uses: docker/build-push-action@v4
-  #       with:
-  #         context: .
-  #         push: true
-  #         tags: ${{ steps.meta.outputs.tags }}
-  #         labels: ${{ steps.meta.outputs.labels }}
-
-  #     - name: Create New Branch with Commit Hash
-  #       env:
-  #         GH_PAT: ${{ secrets.GH_PAT }}
-  #       run: |
-  #         git config user.name Lefisius
-  #         git config user.email lephiafuri@gmail.com
-  #         COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-  #         NEW_BRANCH_NAME="log-$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-' | tr '[:punct:]' '-')"
-  #         git checkout -b $NEW_BRANCH_NAME
-  #         git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
-
   zap_scan:
     runs-on: ubuntu-latest
-    # needs: push_to_registry
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -71,7 +32,7 @@ jobs:
 
       - name: Wait for ZAP to start
         run: |
-          for i in {1..4}; do
+          for i in {1..6}; do
             if curl -s "http://localhost:8081" > /dev/null; then
               echo "ZAP is up and running!"
               break
@@ -79,6 +40,12 @@ jobs:
             echo "Waiting for ZAP to start..."
             sleep 10
           done
+
+          if [ $? -ne 0 ]; then
+            echo "ZAP failed to start. Checking logs..."
+            docker logs zap || echo "No logs available"
+            exit 1
+          fi
 
       - name: Run Spider
         run: |
