cnn

diff --git a/.github/workflows/zap_scan.yml b/.github/workflows/zap_scan.yml
--- a/.github/workflows/zap_scan.yml
+++ b/.github/workflows/zap_scan.yml
@@ -8,43 +8,43 @@ on:
 jobs:
   zap_scan:
     runs-on: ubuntu-latest
-  steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '16.20.2'
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '16.20.2'
 
-    - name: Install dependencies
-      run: npm install --legacy-peer-deps
+      - name: Install dependencies
+        run: npm install --legacy-peer-deps
 
-    - name: Start Angular App
-      run: |
-        nohup ng serve --port 4200 --host 0.0.0.0 &> angular.log &
+      - name: Start Angular App
+        run: |
+          nohup ng serve --port 4200 --host 0.0.0.0 &> angular.log &
+          sleep 60
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Run OWASP ZAP Scan
+        run: |
+          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:4200 -r zap-report.log -J zap-report.json
         sleep 60
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Check if ZAP log exists
+        run: |
+          if [ ! -f zap-report.log ]; then
+            echo "zap-report.log not found!"
+            exit 1
+          fi
 
-    - name: Run OWASP ZAP Scan
-      run: |
-        docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:4200 -r zap-report.log -J zap-report.json
-      sleep 60
-
-    - name: Check if ZAP log exists
-      run: |
-        if [ ! -f zap-report.log ]; then
-          echo "zap-report.log not found!"
-          exit 1
-        fi
-
-    - name: Upload ZAP Log
-      uses: actions/upload-artifact@v3
-      with:
-        name: zap-log
-        path: zap-report.log
+      - name: Upload ZAP Log
+        uses: actions/upload-artifact@v3
+        with:
+          name: zap-log
+          path: zap-report.log
